In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer #It fills the missing value and calculates mean value of the missing values
from sklearn.pipeline import Pipeline

In [13]:
StudentPerformance = pd.read_csv("StudentPerformanceFactors.csv")
StudentPerformance

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [14]:
StudentPerformance.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [15]:
num_cols = StudentPerformance.select_dtypes('number').columns
print(num_cols.tolist())   #num_cols = numerical columns

['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores', 'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score']

In [16]:
cat_cols = StudentPerformance.select_dtypes(exclude = 'number').columns
print(cat_cols.tolist())   #cat_cols = categorical columns

['Parental_Involvement', 'Access_to_Resources', 'Extracurricular_Activities', 'Motivation_Level', 'Internet_Access', 'Family_Income', 'Teacher_Quality', 'School_Type', 'Peer_Influence', 'Learning_Disabilities', 'Parental_Education_Level', 'Distance_from_Home', 'Gender']

`Imputation`

In [17]:
# initializing imputers for numerical and categorical columns

num_imp=SimpleImputer()# by default mean strategy is used ...likhna na likhna 
cal_imp=SimpleImputer(strategy='most_frequent')

In [19]:
StudentPerformance[num_cols]=num_imp.fit_transform(StudentPerformance[num_cols])
StudentPerformance

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23.0,84.0,Low,High,No,7.0,73.0,Low,Yes,0.0,Low,Medium,Public,Positive,3.0,No,High School,Near,Male,67.0
1,19.0,64.0,Low,Medium,No,8.0,59.0,Low,Yes,2.0,Medium,Medium,Public,Negative,4.0,No,College,Moderate,Female,61.0
2,24.0,98.0,Medium,Medium,Yes,7.0,91.0,Medium,Yes,2.0,Medium,Medium,Public,Neutral,4.0,No,Postgraduate,Near,Male,74.0
3,29.0,89.0,Low,Medium,Yes,8.0,98.0,Medium,Yes,1.0,Medium,Medium,Public,Negative,4.0,No,High School,Moderate,Male,71.0
4,19.0,92.0,Medium,Medium,Yes,6.0,65.0,Medium,Yes,3.0,Medium,High,Public,Neutral,4.0,No,College,Near,Female,70.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25.0,69.0,High,Medium,No,7.0,76.0,Medium,Yes,1.0,High,Medium,Public,Positive,2.0,No,High School,Near,Female,68.0
6603,23.0,76.0,High,Medium,No,8.0,81.0,Medium,Yes,3.0,Low,High,Public,Positive,2.0,No,High School,Near,Female,69.0
6604,20.0,90.0,Medium,Low,Yes,6.0,65.0,Low,Yes,3.0,Low,Medium,Public,Negative,2.0,No,Postgraduate,Near,Female,68.0
6605,10.0,86.0,High,High,Yes,6.0,91.0,High,Yes,2.0,Low,Medium,Private,Positive,3.0,No,High School,Far,Female,68.0
6606,15.0,67.0,Medium,Low,Yes,9.0,94.0,Medium,Yes,0.0,Medium,Medium,Public,Positive,4.0,No,Postgraduate,Near,Male,64.0

In [20]:
StudentPerformance.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

`ENCODING`

Encoding Categorical Values

- ONE HOT ENCODING

In [21]:
# features ke liye onehotencoder and labelencoder ka use target ke liye labelence
sex_enc = OneHotEncoder(drop = 'first')
sex_dummy = sex_enc.fit_transform(StudentPerformance[['Gender']]).toarray()
sex_dummy_df = pd.DataFrame(sex_dummy)

drop first, to avoid ```dummy  variable``` trap......
- jab hum onehotencoding krte h to har category ke liye ek new column ban jata h
- agar aap n categories ko input kro to n columns banenge
- lekin inme se ek column humesha baki columns ke combination se predict kiya jaa skta h
- ise kehte h dummy variable trap aur ye multi collinearity create krta h
- jo linear models(jaise experience in job badhega to salary badhegi) ke liye problem ho skti h


```Multicollinearity```
- when more than one independent variable is strongly correlated with another independent variable

In [22]:
sex_dummy_df #strongly correlated - multi-collinearity ...avoid krne hota h ....to avoid multi colinearity we drop one column by using drop = 'first' in OneHotEncoder

        0
0     1.0
1     0.0
2     1.0
3     1.0
4     0.0
...   ...
6602  0.0
6603  0.0
6604  0.0
6605  0.0
6606  1.0

[6607 rows x 1 columns]

In [23]:
cat_cols = ['Parental_Involvement','Access_to_Resources']
cat_enc = OneHotEncoder(drop = 'first')
dummy_cols = cat_enc.fit_transform(StudentPerformance[cat_cols]).toarray()
dummy_df = pd.DataFrame(dummy_cols)

In [25]:
StudentPerformance['Parental_Involvement'].value_counts()

Parental_Involvement
Medium    3362
High      1908
Low       1337
Name: count, dtype: int64

In [27]:
StudentPerformance['Access_to_Resources'].value_counts()

Access_to_Resources
Medium    3319
High      1975
Low       1313
Name: count, dtype: int64

In [28]:
dummy_df

        0    1    2    3
0     1.0  0.0  0.0  0.0
1     1.0  0.0  0.0  1.0
2     0.0  1.0  0.0  1.0
3     1.0  0.0  0.0  1.0
4     0.0  1.0  0.0  1.0
...   ...  ...  ...  ...
6602  0.0  0.0  0.0  1.0
6603  0.0  0.0  0.0  1.0
6604  0.0  1.0  1.0  0.0
6605  0.0  0.0  0.0  0.0
6606  0.0  1.0  1.0  0.0

[6607 rows x 4 columns]

In [29]:
clean_df = pd.concat([StudentPerformance, dummy_df, sex_dummy_df], 
                      axis=1).drop(columns = cat_cols +['Gender'])

`SCALING NUMERIC VALUES`


- standardization or normalization

In [30]:
scaler = StandardScaler()
clean_df[num_cols] = scaler.fit_transform(clean_df[num_cols])
clean_df

,Hours_Studied,Attendance,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,...,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Exam_Score,0,1,2,3,0
0,0.504942,0.348375,No,-0.019796,-0.143800,Low,Yes,-1.213934,Low,Medium,...,0.031411,No,High School,Near,-0.060578,1.0,0.0,0.0,0.0,1.0
1,-0.162822,-1.383736,No,0.661399,-1.116110,Low,Yes,0.411451,Medium,Medium,...,1.001199,No,College,Moderate,-1.602931,1.0,0.0,0.0,1.0,0.0
2,0.671882,1.560853,Yes,-0.019796,1.106313,Medium,Yes,0.411451,Medium,Medium,...,1.001199,No,Postgraduate,Near,1.738833,0.0,1.0,0.0,1.0,1.0
3,1.506587,0.781403,Yes,0.661399,1.592469,Medium,Yes,-0.401242,Medium,Medium,...,1.001199,No,High School,Moderate,0.967657,1.0,0.0,0.0,1.0,1.0
4,-0.162822,1.041220,Yes,-0.700990,-0.699406,Medium,Yes,1.224144,Medium,High,...,1.001199,No,College,Near,0.710598,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,0.838823,-0.950708,No,-0.019796,0.064552,Medium,Yes,-0.401242,High,Medium,...,-0.938377,No,High School,Near,0.196481,0.0,0.0,0.0,1.0,0.0
6603,0.504942,-0.344469,No,0.661399,0.411806,Medium,Yes,1.224144,Low,High,...,-0.938377,No,High School,Near,0.453539,0.0,0.0,0.0,1.0,0.0
6604,0.004119,0.868009,Yes,-0.700990,-0.699406,Low,Yes,1.224144,Low,Medium,...,-0.938377,No,Postgraduate,Near,0.196481,0.0,1.0,1.0,0.0,0.0
6605,-1.665291,0.521587,Yes,-0.700990,1.106313,High,Yes,0.411451,Low,Medium,...,0.031411,No,High School,Far,0.196481,0.0,0.0,0.0,0.0,0.0
6606,-0.830586,-1.123919,Yes,1.342594,1.314666,Medium,Yes,-1.213934,Medium,Medium,...,1.001199,No,Postgraduate,Near,-0.831754,0.0,1.0,1.0,0.0,1.0

In [ ]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression
import seaborn as sns

sns.regplot(x='R&D Spend', y='Profit', data=df)